env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
ignorePatterns:
  - ./src/server/wordLists.js
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  import/no-extraneous-dependencies: 0,
  max-len: 120,
  no-console: 0,
  no-param-reassign: 0,
  no-plusplus: 0,
  no-restricted-globals: 0,
  no-restricted-syntax: 0,
  no-shadow: 0,
  no-underscore-dangle: 0,
  no-use-before-define: 0,
  object-curly-newline: 0,
  react/jsx-filename-extension: 0,
  react/jsx-one-expression-per-line: 0,
  react/no-render-return-value: 0,
  react/no-unescaped-entities: 0,
  react/require-default-props: 0,
}
