env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  import/no-extraneous-dependencies: 0,
  max-len: 0,
  no-console: 0,
  no-param-reassign: 0,
  no-restricted-syntax: 0,
  object-curly-newline: 0,
  react/jsx-filename-extension: 0,
  react/no-render-return-value: 0,
  react/require-default-props: 0,
}
